#!/bin/python3

print ("Here are some information about planets:\n")
print (" 1).Venus 2)Mars 3)Jupiter ")
print (" 4)Saturn 5)Uranus 6)Neptune\n")
weight = 185
planet = int(input("Enter the number for planet"))

if planet == 1:
	weight = weight * 0.91
	print ("On that planet your weigth would be" 'weight')

if planet == 2: 
	weight * = 0.38
	print ("On that planet your weight would be" 'weight')

if planet == 3:
weight * = 2.34
print ("On that planet your weight would be" "weight")

Else
If 
planet == 4
weigth * = 1.06
print ("On that planet your weight would be" "weight")
